### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by albaropereyra22** [S-Ptr/he-voting#1]
Why are you adding 0 to an offset. Is it for readability?![Screenshot_20240216-001727.png](https://github.com/S-Ptr/he-voting/assets/141711575/bdfed16f-d26c-41c6-a0ba-4132f5d00ebf)

**Comment by S-Ptr** [comment]
That's from an ORM class automatically generated by Drogon. Haven't noticed it before and I have no idea why it generates that.
